#!/bin/bash

cd asm
make clean
PATH=../cc65-2.13.3/bin:$PATH make

(
echo "/*"
expand loader.s
echo "*/"
/usr/bin/xxd -i loader | sed 's/loader/loadercode/'

echo "/*"
expand bar.s
echo "*/"
/usr/bin/xxd -i bar | sed 's/bar/barcode/'
) > ../c2d.h.1

cd ..

cat c2d.h.[01] > c2d.h
